### ISSUE TITLE
panlint crashes when template has tab characters

### ISSUE THREAD

**Issue by NZJourneyMan** [quattor/pan#137]
```
marwilso@aardvark:/tmp/template-king$ /ms/dist/elfms/PROJ/panc/10.3-ms1/bin/panlint aquilon/archetype/final.tpl 

<snip>

aquilon/archetype/final.tpl:29: Use dict() instead of nlist()
            SELF[params["name"]] = nlist(
                                   ^^^^^

aquilon/archetype/final.tpl:69: Indentation should be a multiple of four spaces, Spaces should be used instead of tabs Traceback (most recent call last):
  File "/ms/dist/elfms/PROJ/panc/10.3-ms1/bin/panlint", line 414, in <module>
    sys_exit(main())
  File "/ms/dist/elfms/PROJ/panc/10.3-ms1/bin/panlint", line 399, in main
    print_report(*report, vi=args.vi)
  File "/ms/dist/elfms/PROJ/panc/10.3-ms1/bin/panlint", line 195, in print_report
    print print_line(line)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 5: ordinal not in range(128)
```

It looks like the unicode character is coming from this function in panlint:

```python
def print_line(text):                                                                               
    """Return a formatted line of text, replacing tabs with a visible character                     
                                                                                                    
    If stdout is a tty, a unicode rightwards arrow (u2192) will be used for tabs, otherwise the rarely used negation character (\ufffd\ufffd).
    This keeps the character counts in line with fixed-width columns while still making tabs distinguishable in output.
    """                                                                                             
    if stdout.isatty():                                                                             
        text = text.replace('\t', TAB_ARROW)                                                        
    else:                                                                                           
        text = text.replace('\t', '\ufffd\ufffd')                                                             
                                                                                                    
    return ''.join([Fore.GREEN, text.rstrip('\n'), Fore.RESET])                                     
```

This assumes that the terminal can cope with unicode. If the terminal capability is unknown it would be better to use an 8 bit character and the latin codec or even safer, choose a 7 bit character.

This does raise the question of what happens if a templates contains 8 bit characters or some form of utf encoding. If we do support this, instead of arguing with python2.7 and beating it into submission, is it worth considering python3 as it is supposed to handle these problems natively?

**Comment by jrha** [comment]
Whoops.

In terms of the pan compiler, I believe everything is treated as utf-8.

**Comment by jrha** [comment]
Out of interest what terminal are you using?

**Comment by jrha** [comment]
Could you let me know what `python2 -c "import sys; print sys.stdout.encoding"` gives you?

**Comment by NZJourneyMan** [comment]
We are mainly using ANSI_X3.4-1968, otherwise known as pure 7 bit ascii.
