### ISSUE TITLE
Pan thread safety

### ISSUE THREAD

**Issue by stdweird** [quattor/pan#56]
@loomis Brief indication where to look for clues is ok for now.
Looking for a bug in panc (2 consecutive compilation of the same templates lead to different profiles; it used to be harmless (users being specified multiple times in a group), but we are now seeing cases where it is serious (users not appearing in the group anymore)).
One of the possible causes might be the lack of threadsafety in the ListResource and HashResource classes. (see PR #55 for other issues)

Question is: how is pan threaded? what is processed in different threads and what not? eg is a single profile create by processing templates using different threads?

**Comment by gombasg** [comment]
We're seeing both occassional NullPointerException and panc lockups. All seem to be related to TreeMap. Stack trace from a locked compiler (there are 2 threads running with the same stack trace, each eating ~100% CPU):

    "pool-5-thread-3" prio=10 tid=0x00002ac36c009800 nid=0xae1e runnable [0x00002ac3780fe000]
       java.lang.Thread.State: RUNNABLE
           at java.util.TreeMap.getEntry(TreeMap.java:353)
           at java.util.TreeMap.get(TreeMap.java:273)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.ProtectedHashResource.locateUndefinedElement(ProtectedHashResource.java:49)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.dml.data.HashResource.locateUndefinedElement(HashResource.java:132)
           at org.quattor.pan.tasks.Valid1Task$CallImpl.validate(Valid1Task.java:118)
           at org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:92)
           at org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:68)
           at java.util.concurrent.FutureTask.run(FutureTask.java:262)
           at org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
           at org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
           at org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:82)
           at org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:65)
           at java.util.concurrent.FutureTask.run(FutureTask.java:262)
           at org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
           at org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
           at org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:89)
           at org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:61)
           at java.util.concurrent.FutureTask.run(FutureTask.java:262)
           at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
           at java.util.concurrent.FutureTask.run(FutureTask.java:262)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
           at java.lang.Thread.run(Thread.java:724)

I've adapted the example at http://java.dzone.com/articles/concurrency-and-hashmap to TreeMap and indeed I can get it locked up in 2-3 tries.

Limiting the number of CPUs is not realistic - according to top, we utilize 18-20 CPU cores during big compilations, using less would drastically increase the compilation time.

**Comment by gombasg** [comment]
[Issue 6](https://github.com/quattor/pan/issues/6) is another manifestation of the same problem.

**Comment by gombasg** [comment]
I'm trying to add some instrumentation to the code to catch where the race is happening (the NullPointerException happens later, when the TreeMap is already corrupted). One common occurance (but not the only one) is RecordType.setDefaults().

My current suspicion is the copy-on-write handling of HashResource being broken - either a shallow clone operation is missing somewhere, or the mechanism between HashResource.protect() is not completely thread safe. E.g. ProtectedHashResource contains an internal reference to the original HashReference; but I don't see what protects that HashResource to be modified in a different thread, while the current thread does a .get() on the ProtectedHashResource? That could explain TreeMap.get() racing with TreeMap.put(). However, I also see TreeMap.put() racing against another TreeMap.put(), which means the behavior of ProtectedHashResource cannot be the only explnaation, and it may in fact be innocent and the bug can be elsewhere.

**Comment by gombasg** [comment]
[panc_debugging.txt](https://github.com/quattor/pan/files/208794/panc_debugging.txt)

I attached a crude patch I'm using to try to catch the race in action. Unfortunately, so far I was only able to capture one of the threads which are racing. I'm using it on top of 10.2, btw.

**Comment by gombasg** [comment]
Btw. I'm concentrating on HashResource, but ListResource may also be affected. Even if it is, the underlying ArrayList should be much more resistant to corruption than TreeMap, so I expect problems with ListResource harder to see.

**Comment by gombasg** [comment]
Reproducer:

    mkdir -p /tmp/t/inc /tmp/t/obj /tmp/t/out

Create /tmp/t/inc/a.pan as:

```pan
structure template a;
"items" = list(nlist("a", "b"));
```

Create /tmp/t/template_obj as:

```pan
object template @OBJ@;

"/list" = {
    foo = create("a");
    foreach (idx; item; foo["items"]) {
        item["bar"] = "baz";
        append(item);
    };
    SELF;
};
```

Generate a good amount of object templates from the above "template of template":

    for i in `seq 1 20000`; do sed -e "s/@OBJ@/obj_$i/" /tmp/t/template_obj > /tmp/t/obj/obj_$i.pan; done

Compile the generated objects in one go, on a machine with lots of CPU cores (the one I used had 16 cores):

    java -cp /path/to/panc.jar org.quattor.pan.pan_compiler --include-path /tmp/t/obj:/tmp/t/inc --output-dir /tmp/t/out --formats json --nthread 50 /tmp/t/obj/*

(The argument processing which the panc script does takes an awful lot of time, so it is much better to call java directly)

If panc was built with he poisoning patch I've attached above, then I get stack traces like the below one which show exactly where the two threads are trying to call `.put()` on the same HashResource instance simultaneously:

```
evaluation error [/tmp/t/obj/obj_10009.pan:6.9-6.19]
put/put mismatch
me = Thread[pool-5-thread-12: WriteOutputTask(XML, 45, obj_10009): Valid2Task(VALID2, 45, obj_10009): Valid1Task(VALID1, 45, obj_10009): BuildTask(BUILD, 45, obj_10009),5,main],
other = Thread[pool-5-thread-9: WriteOutputTask(XML, 41, obj_1000): Valid2Task(VALID2, 41, obj_1000): Valid1Task(VALID1, 41, obj_1000): BuildTask(BUILD, 41, obj_1000),5,main],
value = { a, b, bar, baz },
Stack trace:
java.lang.Thread.getStackTrace(Thread.java:1552)
org.quattor.pan.dml.data.HashResource.put(HashResource.java:172)
org.quattor.pan.dml.data.Resource.rput(Resource.java:131)
org.quattor.pan.template.BuildContext.setLocalVariable(BuildContext.java:1298)
org.quattor.pan.dml.operators.SetValue.execute(SetValue.java:170)
org.quattor.pan.dml.operators.Assign.execute(Assign.java:65)
org.quattor.pan.dml.DML.execute(DML.java:120)
org.quattor.pan.dml.operators.Foreach.execute(Foreach.java:93)
org.quattor.pan.dml.DML.execute(DML.java:120)
org.quattor.pan.template.BuildContext.executeDmlBlock(BuildContext.java:1037)
org.quattor.pan.statement.AbsoluteAssignmentStatement.execute(AbsoluteAssignmentStatement.java:95)
org.quattor.pan.template.Template.execute(Template.java:413)
org.quattor.pan.tasks.BuildTask$CallImpl.execute(BuildTask.java:155)
org.quattor.pan.tasks.BuildTask$CallImpl.call(BuildTask.java:124)
org.quattor.pan.tasks.BuildTask$CallImpl.call(BuildTask.java:74)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:86)
org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:69)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:82)
org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:65)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:89)
org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:61)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

>>> call stack trace 
>>> [/tmp/t/obj/obj_10009.pan:6.9-6.19]
>>> ====================



evaluation error [/tmp/t/obj/obj_1000.pan:6.9-6.19]
put/put mismatch
me = Thread[pool-5-thread-9: WriteOutputTask(XML, 41, obj_1000): Valid2Task(VALID2, 41, obj_1000): Valid1Task(VALID1, 41, obj_1000): BuildTask(BUILD, 41, obj_1000),5,main],
other = Thread[pool-5-thread-12: WriteOutputTask(XML, 45, obj_10009): Valid2Task(VALID2, 45, obj_10009): Valid1Task(VALID1, 45, obj_10009): BuildTask(BUILD, 45, obj_10009),5,main],
value = { a, b, bar, baz },
Stack trace:
java.lang.Thread.getStackTrace(Thread.java:1552)
org.quattor.pan.dml.data.HashResource.put(HashResource.java:147)
org.quattor.pan.dml.data.Resource.rput(Resource.java:131)
org.quattor.pan.template.BuildContext.setLocalVariable(BuildContext.java:1298)
org.quattor.pan.dml.operators.SetValue.execute(SetValue.java:170)
org.quattor.pan.dml.operators.Assign.execute(Assign.java:65)
org.quattor.pan.dml.DML.execute(DML.java:120)
org.quattor.pan.dml.operators.Foreach.execute(Foreach.java:93)
org.quattor.pan.dml.DML.execute(DML.java:120)
org.quattor.pan.template.BuildContext.executeDmlBlock(BuildContext.java:1037)
org.quattor.pan.statement.AbsoluteAssignmentStatement.execute(AbsoluteAssignmentStatement.java:95)
org.quattor.pan.template.Template.execute(Template.java:413)
org.quattor.pan.tasks.BuildTask$CallImpl.execute(BuildTask.java:155)
org.quattor.pan.tasks.BuildTask$CallImpl.call(BuildTask.java:124)
org.quattor.pan.tasks.BuildTask$CallImpl.call(BuildTask.java:74)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:86)
org.quattor.pan.tasks.Valid1Task$CallImpl.call(Valid1Task.java:69)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:82)
org.quattor.pan.tasks.Valid2Task$CallImpl.call(Valid2Task.java:65)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
org.quattor.pan.cache.AbstractCache.retrieve(AbstractCache.java:137)
org.quattor.pan.cache.AbstractCache.waitForResult(AbstractCache.java:171)
org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:89)
org.quattor.pan.tasks.WriteOutputTask$CallImpl.call(WriteOutputTask.java:61)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
org.quattor.pan.tasks.Task.run(Task.java:58)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

>>> call stack trace 
>>> [/tmp/t/obj/obj_1000.pan:6.9-6.19]
>>> ====================
```

**Comment by gombasg** [comment]
Oops, pressed close by mistake...

**Comment by gombasg** [comment]
Ok, I've just published a pull request. It should be considered RFC at this point, since I know it is not the full story. It makes the test case I've posted above work without triggering the poisoning - at least so far.

**Comment by gombasg** [comment]
I've updated the PR, and I don't see crashes/hangs anymore. Both compilation speed and memory usage takes ~50% hit (there are big variations depending on what do you compile), but the result is now correct.
